version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hospital_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: hospital
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    container_name: hospital_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:adminpassword@db:5432/hospital
      JWT_SECRET: your-secret-key
      PORT: 3000
      CORS_ORIGIN: http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000
    container_name: hospital_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
